import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import NavTab from '@/Components/Navbar'
import '../node_modules/bootstrap/dist/css/bootstrap.min.css';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Galaxy Removals Sydney</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <NavTab/>
      <main>
          <div className={styles.pageContainer}>
            <section className={styles.heroContainer}>
                <div className={styles.hero}>We ___ <br></br>so <em>he</em> doesn&apos;t have to</div>
                <div><Image className={styles.dogImage} height={2800} width={4000} src="/dogHero.jpg"></Image></div>
            </section>
          </div>
      </main>
    </>
  )
}

const styles = {
  pageContainer: "h-[100vh] flex flex-col",
  heroContainer: "h-[60vh] flex flex-col w-[100vw]",
  dogImage: "w-full h-full static",
  hero: "absolute text-3xl pl-8 left-12 top-72"
}
