import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import NavTab from '@/Components/Navbar'
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
// import '../node_modules/bootstrap/dist/css/bootstrap.min.css';
import CardGrid from '@/Components/CardGrid'
import Footer from '@/Components/Footer' 
import style from '../styles/Home.module.css'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Galaxy Removals Sydney</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="../styles/Home.module.css" rel="stylesheet"/>
      </Head>
    <NavTab className={styles.nav}/>
      <main>
          <div className={styles.pageContainer}>
            <div className=" z-40 relative">
              <section className={styles.heroContainer}>
                {/* <div className="relative w-[40vw] flex flex-col"> */}
                  <div className={styles.hero}>We handle the <span id="cycle"></span> <br></br>so <em>he</em> doesn&apos;t have to</div>
                  <div className='bg-red-500 absolute z-40 mt-24 md:text-2xl xs:text-lg w-2/3 md:bottom-28 xs:bottom-20 text-white p-2 lg:p-6 cursor-pointer rounded-r-3xl'><a href="/pricing#contact">Book removals</a></div>
                  <div className='bg-red-500 absolute z-40 mt-24 md:text-2xl xs:text-lg w-2/3 md:bottom-10 xs:bottom-6 text-white p-2 lg:p-6 cursor-pointer rounded-r-3xl'><a href="/pricing#contact">Book packing</a></div>

                {/* </div> */}
                  
                

                  <div><Image className={styles.dogImage} height={2800} width={4000} src="/dogHero.jpg"></Image></div>
              </section>
            </div>
            <section className={styles.bio}>
            <div className={styles.experience}>100% owner-operated for almost 35 years </div>
            
            <CardGrid className="p-4"/>
            
            </section>
            <Container id="services" className="p-0 m-0" fluid xs={{ gutter: 0 }}>
                <Row xs={{ gutter: 0 }}  noGutters={true} className="pr-0 gutter-x-0">
                  <Col xs={12} md={6} className="d-flex flex-col justify-center bg-blue-100 p-12">
                      <div className={styles.sectionTitle}>House and apartment relocations</div>
                      <ul className={styles.sectionList}>
                        <li className="flex gap-3 align-center items-center"><Image height={40} width={40} src="/tick.png"></Image>Residental moves of all sizes and complexities</li>
                        <li className="flex gap-3 align-center items-center"><Image height={40} width={40} src="/tick.png"></Image><strong>Free</strong>box rental</li>
                        <li className="flex gap-3 align-center items-center"><Image height={40} width={40} src="/tick.png"></Image>Difficult access consultation</li>
                        <li className="flex gap-3 align-center items-center"><Image height={40} width={40} src="/tick.png"></Image>Range of <a href="/#pricing">rates</a>avaliable</li>
                      </ul>
                      <div className={styles.buttonContainer}>
                          <div className={styles.imageButton}><strong>Let&apos;s talk moving</strong></div>
                      </div>
                  </Col>
                  <Col xs={12} md={6} className="px-0 relative">
                    <Image className={styles.storeImage} height={200} width={400} src="/openbox.jpg"></Image>
                    <div className='bg-red-500 z-40 absolute top-10 text-white p-6 cursor-pointer rounded-r-3xl'><a href="/pricing#rates">Check our rates</a></div>
                  </Col>
                </Row>

                <Row xs={{ gutter: 0 }} noGutters={true} className="d-flex flex-row-reverse">
                  <Col xs={12} md={6} className=" d-flex flex-col justify-center bg-yellow-100 p-12">
                      <div className={styles.sectionTitle}>Local self-storage <strong>experts</strong> </div>
                      <ul className={styles.sectionList}>
                        <li className="flex gap-3 align-center items-center"><Image height={40} width={40} src="/tick.png"></Image>Short-term and long-term solutions</li>
                        <li className="flex gap-3 align-center items-center"><Image height={40} width={40} src="/tick.png"></Image>7-day-a-week access</li>
                        <li className="flex gap-3 align-center items-center"><Image height={40} width={40} src="/tick.png"></Image>All sized units avaliable</li>
                        <li className="flex gap-3 align-center items-center"><Image height={40} width={40} src="/tick.png"></Image>All move-in logistics handled by us</li>
                      </ul>
                      <div className={styles.buttonContainer}>
                          <div className={styles.imageButton}><strong>Let&apos;s talk storage</strong></div>
                      </div>
                  </Col>
                  <Col xs={12} md={6} className="px-0">
                    <Image className={styles.storeImage} height={200} width={400} src="/storage.jpg"></Image>
                  </Col>
                </Row>

                <Row lg={{ gutter: 0 }}  noGutters={true} className={styles.storageContainer}>
                  <Col xs={12} md={6} className="d-flex flex-col justify-center bg-blue-100 p-12">
                      <div className={styles.sectionTitle}>Office and warehouse relocations</div>
                      <ul className={styles.sectionList}>
                        <li className="flex gap-3 align-center items-center"><Image height={40} width={40} src="/tick.png"></Image>Experienced in office moves of all sizes</li>
                        <li className="flex gap-3 align-center items-center"><Image height={40} width={40} src="/tick.png"></Image>Small warehouse relocations and logistics</li>
                        <li className="flex gap-3 align-center items-center"><Image height={40} width={40} src="/tick.png"></Image>Hard access consultation</li>
                        <li className="flex gap-3 align-center items-center"><Image height={40} width={40} src="/tick.png"></Image>Call to organise a free quote</li>
                      </ul>
                      <div className={styles.buttonContainer}>
                          <div className={styles.imageButton}><strong>Let&apos;s talk office moves</strong></div>
                      </div>
                  </Col>
                  <Col xs={12} md={6} className="px-0"><Image className={styles.storeImage} height={200} width={400} src="/office.jpg"></Image></Col>
                </Row>

                <Row xs={{ gutter: 0 }} noGutters={true} className="d-flex flex-row-reverse">
                  <Col xs={12} md={6} className=" d-flex flex-col justify-center bg-yellow-100 p-12">
                      <div className={styles.sectionTitle}>Packing and unpacking</div>
                      <ul className={styles.sectionList}>
                        <li className="flex gap-3 align-center items-center"><Image height={40} width={40} src="/tick.png"></Image>Either full house or last minute bits</li>
                        <li className="flex gap-3 align-center items-center"><Image height={40} width={40} src="/tick.png"></Image>Standard rates</li>
                        <li className="flex gap-3 align-center items-center"><Image height={40} width={40} src="/tick.png"></Image>All returnable materials and boxes supplied Free</li>
                      </ul>
                      <div className={styles.buttonContainer}>
                          <div className={styles.imageButton}><strong>Let&apos;s talk storage</strong></div>
                      </div>
                  </Col>
                  <Col xs={12} md={6}  className="px-0">
                    <Image className={styles.storeImage} height={200} width={400} src="/packing.jpg"></Image>
                  </Col>
                </Row>

            </Container>
            <Footer className={styles.footer}/>
          </div>
          
      </main>
      
    </>
  )
}

const styles = {
  pageContainer: "h-[100vh] w-[100vw] flex flex-col",

  heroContainer: "mt-20 h-contain w-contain ",
  dogImage: "w-full h-full z-0",
  hero: "font-serif hidden sm:block absolute text-2xl top-56 pl-9 md:text-3xl lg:text-5xl pl-5 md:left-6 lg:pl-6 lg:left-16 lg:top-72 ",
  heroTab: " border-2 right-0 h-56 w-2/5 bg-blue-400 rounded-2xl",

  bio: "",
  experience: "font-serif flex items-center justify-center py-12 pt-24 pb-5 text-center text-xl mx-5 lg:text-4xl word-wrap",

  // storageContainer: " flex flex-col w-[100vw] h-full lg:flex-row bg-yellow-100",
  //   section: "flex flex-1 flex-col mt-12 text-left",
      sectionTitle: "text-center text-2xl sm:text-3xl lg:text-4xl mb-12",
      sectionList: "text-m lg:text-xl text-left gap-4 justify-center align-center",

    storeImage: "h-full w-full",
    buttonContainer: "flex justify-center items-center w-full mt-12",
    imageButton: "bottom-20 left-56 w-fit p-2 rounded-2xl bg-green-400 border-2 border-white",


  // interstateContainer: "flex w-[100vw] h-full flex-col lg:flex-row-reverse bg-blue-100",
}
